In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('vendas_brasil_aula3_bruto.csv')

df.head()
df.tail()

,pedido_id,data,uf,canal,categoria,produto,cliente_id,quantidade,receita,lucro,observacao
223,1180,2024-03-11,SC,Loja Física,Telefonia,Smartphone X,C158,1,2563.44,415.42,NaN
224,1015,2024-02-26,RS,Online,Informática,Notebook Pro,C102,3,15011.49,NaN,cliente premium
225,1115,2024-07-29,MG,Loja Física,Informática,Notebook Pro,C144,3,12566.04,2879.76,NaN
226,1172,2024-11-11,ES,Loja Física,Informática,Notebook Pro,C128,3,13154.04,3408.22,entrega rápida
227,1209,2024-05-27,MG,Marketplace,Áudio,Caixa de Som,C121,2,810.2,282.52,NaN

In [13]:
df.shape
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   pedido_id   228 non-null    int64
 1   data        228 non-null    object
 2   uf          223 non-null    object
 3   canal       223 non-null    object
 4   categoria   223 non-null    object
 5   produto     228 non-null    object
 6   cliente_id  228 non-null    object
 7   quantidade  228 non-null    int64
 8   receita     226 non-null    object
 9   lucro       222 non-null    float64
 10  observacao  178 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 19.7+ KB

pedido_id      0
data           0
uf             5
canal          5
categoria      5
produto        0
cliente_id     0
quantidade     0
receita        2
lucro          6
observacao    50
dtype: int64

In [14]:
df['data'] = pd.to_datetime(df['data'], errors='coerce')

df['receita'] = pd.to_numeric(df['receita'], errors='coerce')
df['lucro'] = pd.to_numeric(df['lucro'], errors='coerce')
df['quantidade'] = pd.to_numeric(df['quantidade'], errors='coerce')

In [15]:
df = df.dropna(subset=['data'])

df['receita'] = df['receita'].fillna(0)
df['lucro'] = df['lucro'].fillna(0)

In [16]:
df = df.drop_duplicates()

In [21]:
df['uf'] = df['uf'].str.upper().str.strip()
df['canal'] = df['canal'].str.lower().str.strip()
df['categoria'] = df['categoria'].str.lower().str.strip()

In [18]:
df['ano'] = df['data'].dt.year
df['mes'] = df['data'].dt.month
df['ano_mes'] = df['data'].dt.to_period('M').astype(str)

df['margem_lucro'] = df['lucro'] / df['receita']
df['margem_lucro'] = df['margem_lucro'].replace([np.inf, -np.inf], np.nan)

In [19]:
df_clean = df[
    ['data','ano','mes','ano_mes','uf','canal','categoria',
     'receita','lucro','quantidade','margem_lucro']
]

In [20]:
df_clean.to_csv('vendas_brasil_aula3_clean.csv', index=False)

In [22]:
df.info()
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 154
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   pedido_id     4 non-null      int64
 1   data          4 non-null      datetime64[ns]
 2   uf            4 non-null      object
 3   canal         4 non-null      object
 4   categoria     4 non-null      object
 5   produto       4 non-null      object
 6   cliente_id    4 non-null      object
 7   quantidade    4 non-null      int64
 8   receita       4 non-null      float64
 9   lucro         4 non-null      float64
 10  observacao    2 non-null      object
 11  ano           4 non-null      int32
 12  mes           4 non-null      int32
 13  ano_mes       4 non-null      object
 14  margem_lucro  3 non-null      float64
dtypes: datetime64[ns](1), float64(3), int32(2), int64(2), object(7)
memory usage: 480.0+ bytes

,pedido_id,data,uf,canal,categoria,produto,cliente_id,quantidade,receita,lucro,observacao,ano,mes,ano_mes,margem_lucro
0,1000,2024-04-29,SP,loja física,informática,Notebook Pro,C134,1,4535.11,1289.83,ok,2024,4,2024-04,0.284410
17,1017,2024-09-30,SP,marketplace,periféricos,Mouse Gamer,C145,2,0.00,237.40,ok,2024,9,2024-09,NaN
101,1101,2024-10-21,MG,marketplace,telefonia,Smartphone X,C151,4,11466.36,2087.05,NaN,2024,10,2024-10,0.182015
154,1154,2024-09-30,RS,loja física,informática,Notebook Pro,C155,1,3998.83,641.54,NaN,2024,9,2024-09,0.160432